### ISSUE TITLE
Does not work with Magento 2.3 anymore

### ISSUE THREAD

**Issue by allrude** [faranaky/magento2-simple-menu#1]
Hi i'm was experimenting with this module but since Magento 2.3 it doesn't work anymore, no errors but it just doesn't show in the backend, any idea's

**Comment by faranaky** [comment]
Dear Allrude,

Thanks for reporting this issue.
I've made the codes compatible with version 2.3.
Please use this branch for getting updated codes: [version_2.3](https://github.com/faranaky/magento2-simple-menu/tree/feature/version_2.3)

Regards,
Faranak

**Comment by faranaky** [comment]
> Hi i'm was experimenting with this module but since Magento 2.3 it doesn't work anymore, no errors but it just doesn't show in the backend, any idea's
@allrude can I close this issue?

**Comment by allrude** [comment]
Hi Faranaky, thanks for the fix, works fine, i did a clean M2.3 Install and tested the menu-module and had no problems.

greetings

Ruud
