### ISSUE TITLE
Stoped working with Magento 2.3.5-p1

### ISSUE THREAD

**Issue by allrude** [faranaky/magento2-simple-menu#2]
Hi Faranak Yazdanfar, The module doesn't work anymore under Magento 2.3.5, it looks like the settings don't save, if I choose CMS page it is set to category again after save. 

Hope you have time to look in to this Issue

Greetings

Ruud

**Comment by zapateroremendon** [comment]
Hi,
It looks very useful module, however It is not compiling on magento 2.3.5 :( 

Incompatible argument type: Required type: \Magento\Catalog\Model\ResourceModel\Category\StateDependentCollectionFactory. Actual type: \Magento\Catalog\Model\ResourceModel\Category\CollectionFactory; File:
/home/user/public_html/app/code/Fary/SimpleMenu/Block/Megamenu.php

regards,

**Comment by allrude** [comment]
Hi @faranaky and @zapateroremendon,

I solved this error and got it working on 2.3.5-p2 and 2.3.4, 
Since I contacted @faranaky and she mentioned no longer working on Magento,
I cloned the repro and made it my own ( i needed a lot of customization )

so i now longer took the effort to make a proper Pull request to this Repro,
But I will share the fix here for you to use

_fixing the Magento side_

Change line 16 in MegaMenu.php to;

```public function __construct(\Magento\Catalog\Helper\Category $catalogCategory, \Magento\Catalog\Model\ResourceModel\Category\StateDependentCollectionFactory```

So replacing CollectionFactory to StateDependentCollectionFactory

_fixing the PHP side_

Change line 93 in TopMenu.php to;

```if ($colBrakes && count($colBrakes) && $colBrakes[$counter]['colbrake']) {```

and line 256 to;

```        if ($colBrakes && count($colBrakes) && $limit) {```

So in both adding $colBrakes &&

After that the Module works as expected

Greetings and stay Safe

Ruud

**Comment by zapateroremendon** [comment]
HI @allrude
Thanks for your contribution ! however I am on trouble since I can not see line 256 at TopMenu.php as you reference: if (count($colBrakes) && $limit) {

regards,
